# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2062c6e9a643e246d093976ecf048ca6e5a212cf4aa6acbfb5077d502c36f1f4cbc96277708a17261bfd4fc232e428dec8cabfdd05067343d309b0072737ace

test:
  secret_key_base: e17437151f01724784ad6ec420e9bb2e6ca9359f6e1177b8746998c6a70873de6a31b8b57f6ff72ec753893d3fa901fa2afe3862a8cac1c0bed080fa70c42856

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
